### ISSUE TITLE
Is redstone dead?

### ISSUE THREAD

**Issue by kaendfinger** [luizmineo/redstone.dart#61]
I am praying that redstone isn't dead! I love it too much!

**Comment by luizmineo** [comment]
No, it's not. I'm working on the v0.6 version for a while, and I hope to publish it on github soon. Stay tuned!

**Comment by kaendfinger** [comment]
:) Thanks. You are awesome.

**Comment by iamsalnikov** [comment]
> You are awesome

:+1:

**Comment by kaendfinger** [comment]
@luizmineo What is the status of v0.6? If it will be awhile, can you detail what's new?

**Comment by luizmineo** [comment]
Well, it's taking more time than I had planned, but it's almost 60% done.

The main goal of this version is to reorganize the entire implementation of Redstone, which will make the code more easy to maintain and evolve. Also, I'm taking the opportunity to polish the API, and add some other cool features (which were nearly impossible to implement in the current version, see below). The downside is that this version introduces some breaking changes, but I think it's for the best.

Some highlights of this version are:

 * **A new library layout**: If you take a close look at the current code base, you'll see that the entire logic of the framework is compressed in only two main files: `src/setup_impl.dart` and `src/server_impl.dart`. This structure worked well in the early versions of the framework, when it had only the basic features, but now the code base is just a huge mess. In v0.6, the framework is organized in several libraries, and each one can be easily tested. Moreover, this version is already using the new experimental features (async/await and enum).

* **A new way to build interceptors**: The chain API is now entirely Future based, and interceptors can be written more naturally. For example, a basic CORS interceptor can now be written as follow:

```dart
@Interceptor("/.*")
Future corsInterceptor() async {
  await chain.next();
  return response.change(headers: {
    "Access-Control-Allow-Origin": "*"
  });
} 
```

Also, routes and error handlers have received new features.

* **Improved plugin API**: The current plugin API doesn't handle asynchronous operations very well (for example, a parameter provider can't use asynchronous operations to produce a value). This was fixed in v0.6

* **A new dispatcher function**: If you are familiar with the JEE API, you already know what request dispatcher means. It allows you to include other resources to your response. This feature is useful to implement server-side template processing, for example.

Right now, v0.6 is incomplete and broken :( so I will publish it only when it achieves a usable state. I can't promise a release date, since the framework is developed in my spare time, but I hope to release it in the near future.

**Comment by kaendfinger** [comment]
@luizmineo I like to donate to people who do amazing things with Dart btw, so if you would like to open up a donation page, I would be glad to help!

**Comment by luizmineo** [comment]
The first alpha release is available for test. See https://github.com/luizmineo/redstone.dart/tree/v0.6

**Comment by kaendfinger** [comment]
Thanks!
