### ISSUE TITLE
Use enums for HTTP methods.

### ISSUE THREAD

**Issue by austincummings** [luizmineo/redstone.dart#80]
All HTTP methods under `package:redstone/server.dart` are just const strings. These should be enum's for when that functionality lands. It would also be cool if all HTTP methods could be put into this new enum.

**Comment by luizmineo** [comment]
[Redstone v0.6](https://github.com/luizmineo/redstone.dart/tree/v0.6) already uses enums for data types (json, form, text...). Although, since the [http protocol](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) doesn't restrict the method types that a request can use, I didn't find it safe to restrict Redstone to the common methods.

**Comment by austincummings** [comment]
Ah, makes sense. Then would it be possible to get the rest of the common HTTP methods declared as `const String`'s  then? For example the methods shown [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.2).

**Comment by luizmineo** [comment]
Yes, that's a good idea. Thanks

**Comment by luizmineo** [comment]
Fixed in [v0.6.0-alpha.3](https://github.com/luizmineo/redstone.dart/tree/v0.6)
